services:
  nest-boilerplate:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nest-boilerplate
    env_file:
      - .env.production.local
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
